sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: MhYOnY9fCPEBXEPpulVEMxPYP/t+c+bJAHP/7KPd5G9k8fj+v7QwmAmVb9GY5FORum9ojrRs9kmf2oZsk5hTh8xbiEJssqV9FHAEh9dEWYmEJ10gCV1PdGUZ/B8V0UnfxX6za4FNyojUTrz+oHnhIQ1mseligXXiJA+mCJrpYH+FbATf3YBmlv2bo6M6IH0eXaI/Nhvy3KkeuirQqX5SU1PSevsQ2HbL+4tkbhDZYcbROJOMrZldwMeassmrfNbu0lvd7ZwOgXdrAHZMTc4Adi0vkVrK09E75aKxa34s3k+jJ3mjRBA+HmXaMcgeZiQc8Eko1CF9dQTUePx5xIyYOTk5EAPRfLpkLMc7CrpjYVvppWFKiolTWa7FDadbxJJWLHOu0AwKyB44XFWV/D6DD30hqfUxge2CoRER1g6rM7GGbGYPJAbNON7AT6TnMe9CQOVdtSvl6Tn3tJMPm+BSSY2ugrEOu0kxn37nZste21X1Nb09sEZhaPwddND3jW/I+s1YvunLRp8vhBjlpcfTRYtbEMWe0+ETVMLsj5Oxb2r4ROKpVruDETr4gHXfBsb6Q2UveGTFSpQsMZKrhFEntMQRslhvnLHTSt/nn0cN+8qpHLSAwMVJakxD631Ntuvza/n6pQUAL7W/Y9vRVJcWX97wZPKXFSWkQh/6NAqVEPI=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: BjZLN2M78UD0VQyWUvFjErqcVMUW7h3utRoVuRsjQUp4ajNHqrG9o/MA8Ci41b99ZPrf5sd0lJAGXbMtZCUft/7Eh80lE09PwujdvosRBVNSu0JdIEPGd+UG9ERAUNYD8p/8QLFXTLfQkUNAD3SrPavWBFZm2LWkWR0jns7CdKoRfaVWgNSy8+/XfIAg56nsPonLnYz8hxd8GP4D1vKv4OTdDiT9UlMDza+drCnonOD2aGhvKBiC5OVNiCcmzH+etztSmRR3C7GnENU+Ux2qVnY/aby0FeCsSidUGXNBllxZgA5vK8JgKsaHgr6na/mqzMAFXIrjjnEB/z789/cHEM1X/Md5CgAf2/kbiu+15A2o/m3Jh98igzPmbgx/xQUYhSj8PFi0CYPXPA/KM1S0qEUQsB/6LrM4FFM130nD8zkqcOkpfGGdCQ5uWFGj0ZE3RQ/XXqHA09cNjPEWlhDXolfOansVEBJJlHh1+PaZhiXqJqef7xapyBkm7b6vFnjfmOYA1GOqN349+UE01G/jDP4YBCYlcUQiIl69gbPSOeYpwf3ov3tlJVzwn/KJk4J+BQhgyNDEPb/wt1yOFb0hlkk4gcus1ApNQJHTXZj/N3jtZMM6Hqyy0jJQz9fPr4p0NugA1TXTXA7mPdAtwgQ2IXdtjBZzcrvD+Ga8f3DW5e0=
